export default {
  login: "charles-op",
  id: 123382265,
  node_id: "U_kgDOB1qp-Q",
  avatar_url: "https://avatars.githubusercontent.com/u/123382265?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/charles-op",
  html_url: "https://github.com/charles-op",
  followers_url: "https://api.github.com/users/charles-op/followers",
  following_url:
    "https://api.github.com/users/charles-op/following{/other_user}",
  gists_url: "https://api.github.com/users/charles-op/gists{/gist_id}",
  starred_url: "https://api.github.com/users/charles-op/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/charles-op/subscriptions",
  organizations_url: "https://api.github.com/users/charles-op/orgs",
  repos_url: "https://api.github.com/users/charles-op/repos",
  events_url: "https://api.github.com/users/charles-op/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/charles-op/received_events",
  type: "User",
  site_admin: false,
  name: "Charles Opwonya",
  company: null,
  blog: "",
  location: "Tel Aviv",
  email: null,
  hireable: null,
  bio: "Front End Developer",
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2023-01-23T13:30:48Z",
  updated_at: "2023-10-06T20:15:53Z",
};
